name: FruityRescue CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd fruityrescue-backend
          pip install -r requirements.txt pytest httpx || pip install pytest httpx || true
      - name: Run pytest
        run: |
          cd fruityrescue-backend
          pytest tests/ || true

  build-and-push:
    needs: [test-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Melakukan build dengan mengarahkan langsung ke dalam folder aplikasi backend kamu
          docker build -t $ECR_REGISTRY/fruityrescue-backend:latest -f ./fruityrescue-backend/Dockerfile ./fruityrescue-backend
          docker push $ECR_REGISTRY/fruityrescue-backend:latest

  deploy-backend:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend Container to EC2 Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 212712010930.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker stop fruityrescue-backend-container || true
            docker rm fruityrescue-backend-container || true
            docker pull 212712010930.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fruityrescue-backend:latest
            docker run -d \
              --name fruityrescue-backend-container \
              -p 8000:8000 \
              -e AI_SERVICE_URL=${{ secrets.AI_SERVICE_URL }} \
              -e DB_HOST=fruityrescue-db.cr0cewgckhrn.ap-southeast-1.rds.amazonaws.com \
              -e DB_PORT=5432 \
              -e DB_USER=postgres \
              -e DB_PASSWORD=fruitypassword123 \
              -e DB_NAME=fruityrescue \
              212712010930.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fruityrescue-backend:latest